version: '3.7'
services:
  oidc-front:
    container_name: oidc-front
    build:
      context: oidc-front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SECRET: ${SECRET}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      REDIRECT_URI: ${REDIRECT_URI}
      COOKIE_SECURE: ${COOKIE_SECURE}
    volumes:
      - ./oidc-front:/usr/src/app
